create table if not exists public.eighteen_zero_games (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  display_name text not null,
  score numeric(5,1) not null check (score between 0 and 100),
  record text not null,
  lineup jsonb not null default '[]'::jsonb,
  coach jsonb,
  events jsonb not null default '[]'::jsonb,
  scores jsonb not null default '{}'::jsonb,
  mvp jsonb,
  key_player jsonb,
  used_reroll boolean not null default false,
  random_factor integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists eighteen_zero_games_user_created_at_idx
on public.eighteen_zero_games (user_id, created_at desc);

create index if not exists eighteen_zero_games_score_idx
on public.eighteen_zero_games (score desc, created_at asc);

alter table public.eighteen_zero_games enable row level security;

drop policy if exists eighteen_zero_games_owner_select on public.eighteen_zero_games;
create policy eighteen_zero_games_owner_select on public.eighteen_zero_games
for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists eighteen_zero_games_admin_select on public.eighteen_zero_games;
create policy eighteen_zero_games_admin_select on public.eighteen_zero_games
for select to authenticated
using (public.current_user_role() = 'admin');

drop policy if exists eighteen_zero_games_owner_insert on public.eighteen_zero_games;
create policy eighteen_zero_games_owner_insert on public.eighteen_zero_games
for insert to authenticated
with check ((select auth.uid()) = user_id);

revoke all on table public.eighteen_zero_games from anon, authenticated;
grant select, insert on table public.eighteen_zero_games to authenticated;
grant usage, select on sequence public.eighteen_zero_games_id_seq to authenticated;
