create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text not null,
  role text not null default 'member' check (role in ('admin', 'editor', 'member')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.eighteen_zero_scores (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  display_name text not null,
  best_score numeric(5,1) not null check (best_score between 0 and 100),
  last_score numeric(5,1) not null check (last_score between 0 and 100),
  best_record text not null,
  games_played integer not null default 1 check (games_played > 0),
  updated_at timestamptz not null default now()
);

create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon;
grant usage on schema private to authenticated;

create or replace function private.current_user_role()
returns text
language sql
security definer
set search_path = ''
stable
as $$
  select role from public.profiles where id = (select auth.uid())
$$;

revoke execute on function private.current_user_role() from public, anon;
grant execute on function private.current_user_role() to authenticated;

create or replace function public.current_user_role()
returns text
language sql
security invoker
set search_path = ''
stable
as $$
  select private.current_user_role()
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    'member'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

revoke execute on function public.handle_new_user() from public, anon, authenticated;

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  number text,
  team text not null check (team in ('masculine', 'feminine', 'staff')),
  position text,
  height text,
  seniority text,
  instagram text,
  poster_url text,
  profile_text text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.players add column if not exists profile_text text;

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  team text not null check (team in ('masculine', 'feminine')),
  season text not null,
  phase text,
  match_date date not null,
  match_time time,
  rival text not null,
  venue text,
  court text,
  our_score integer,
  rival_score integer,
  status text not null default 'scheduled' check (status in ('scheduled', 'finished', 'postponed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_stats (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  minutes text,
  points integer not null default 0,
  field_goals text,
  three_pointers text,
  free_throws text,
  offensive_rebounds integer,
  defensive_rebounds integer,
  fouls integer,
  steals integer,
  turnovers integer,
  blocks integer,
  assists integer,
  valuation numeric,
  created_at timestamptz not null default now(),
  unique (match_id, player_id)
);

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  reason text not null,
  status text not null default 'new' check (status in ('new', 'read', 'answered', 'archived')),
  created_at timestamptz not null default now()
);

create table if not exists public.news_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text unique not null,
  excerpt text not null,
  body text not null,
  cover_url text,
  category text not null default 'Club',
  author text,
  published boolean not null default false,
  featured boolean not null default false,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.news_posts add column if not exists author text;

create table if not exists public.site_content (
  key text primary key,
  section text not null check (section in ('quick_links', 'social', 'sponsor', 'home_highlights', 'home_intro', 'home_cards', 'footer_text')),
  label text not null,
  href text not null,
  type text not null default 'internal' check (type in ('text', 'internal', 'instagram', 'youtube', 'twitch', 'website')),
  visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_content drop constraint if exists site_content_section_check;
alter table public.site_content add constraint site_content_section_check
  check (section in ('quick_links', 'social', 'sponsor', 'home_highlights', 'home_intro', 'home_cards', 'footer_text'));
alter table public.site_content drop constraint if exists site_content_type_check;
alter table public.site_content add constraint site_content_type_check
  check (type in ('text', 'internal', 'instagram', 'youtube', 'twitch', 'website'));

create table if not exists public.banquiger_teams (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  season text not null,
  name text not null,
  budget numeric not null default 100,
  total_points numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, season)
);

create table if not exists public.banquiger_rosters (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.banquiger_teams(id) on delete cascade,
  match_id bigint references public.matches(id) on delete set null,
  player_id bigint not null references public.players(id) on delete cascade,
  slot text not null check (slot in ('base', 'escolta', 'alero', 'ala_pivot', 'pivot', 'bench_1', 'bench_2')),
  purchase_price numeric not null default 0,
  created_at timestamptz not null default now(),
  unique (team_id, match_id, slot)
);

alter table public.profiles enable row level security;
alter table public.eighteen_zero_scores enable row level security;
alter table public.players enable row level security;
alter table public.matches enable row level security;
alter table public.player_stats enable row level security;
alter table public.contact_messages enable row level security;
alter table public.news_posts enable row level security;
alter table public.site_content enable row level security;
alter table public.banquiger_teams enable row level security;
alter table public.banquiger_rosters enable row level security;

-- Configuración editable de los juegos. Cada documento conserva el mismo formato
-- que utilizan los paneles y permite evolucionar las mecánicas sin migraciones por campo.
create table if not exists public.game_data (
  key text primary key,
  game text not null check (game in ('banquiger', 'eighteen-zero')),
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_game_data (
  user_id uuid not null references public.profiles(id) on delete cascade,
  key text not null,
  game text not null check (game in ('banquiger', 'eighteen-zero')),
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

alter table public.game_data enable row level security;
alter table public.user_game_data enable row level security;

alter table public.banquiger_teams add column if not exists selected_ids jsonb not null default '[]'::jsonb;
alter table public.banquiger_teams add column if not exists selected_match_id bigint references public.matches(id) on delete set null;
alter table public.banquiger_teams add column if not exists manager_name text;

drop policy if exists game_data_public_read on public.game_data;
create policy game_data_public_read on public.game_data for select to anon, authenticated using (true);

drop policy if exists game_data_admin_insert on public.game_data;
create policy game_data_admin_insert on public.game_data for insert to authenticated
with check (public.current_user_role() = 'admin');

drop policy if exists game_data_admin_update on public.game_data;
create policy game_data_admin_update on public.game_data for update to authenticated
using (public.current_user_role() = 'admin') with check (public.current_user_role() = 'admin');

drop policy if exists game_data_admin_delete on public.game_data;
create policy game_data_admin_delete on public.game_data for delete to authenticated
using (public.current_user_role() = 'admin');

drop policy if exists user_game_data_owner_select on public.user_game_data;
create policy user_game_data_owner_select on public.user_game_data for select to authenticated
using (user_id = auth.uid());

drop policy if exists user_game_data_owner_insert on public.user_game_data;
create policy user_game_data_owner_insert on public.user_game_data for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists user_game_data_owner_update on public.user_game_data;
create policy user_game_data_owner_update on public.user_game_data for update to authenticated
using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists user_game_data_owner_delete on public.user_game_data;
create policy user_game_data_owner_delete on public.user_game_data for delete to authenticated
using (user_id = auth.uid());

drop policy if exists banquiger_teams_owner_select on public.banquiger_teams;
create policy banquiger_teams_owner_select on public.banquiger_teams for select to authenticated
using (user_id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists banquiger_teams_owner_insert on public.banquiger_teams;
create policy banquiger_teams_owner_insert on public.banquiger_teams for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists banquiger_teams_owner_update on public.banquiger_teams;
create policy banquiger_teams_owner_update on public.banquiger_teams for update to authenticated
using (user_id = auth.uid() or public.current_user_role() = 'admin')
with check (user_id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin on public.profiles
for select to authenticated using (
  id = (select auth.uid())
  or (select private.current_user_role()) = 'admin'
);

drop policy if exists profiles_update_own_or_admin on public.profiles;
create policy profiles_update_own_or_admin on public.profiles
for update to authenticated
using ((select private.current_user_role()) = 'admin')
with check ((select private.current_user_role()) = 'admin');

drop policy if exists eighteen_zero_scores_authenticated_read on public.eighteen_zero_scores;
create policy eighteen_zero_scores_authenticated_read on public.eighteen_zero_scores
for select to authenticated
using (true);

revoke all on table public.eighteen_zero_scores from anon, authenticated;
grant select on table public.eighteen_zero_scores to authenticated;

create or replace function public.submit_eighteen_zero_score(p_score numeric)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_display_name text;
  v_score numeric(5,1);
  v_record text;
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesión para guardar tu puntuación.';
  end if;

  v_score := round(p_score, 1);
  if v_score is null or v_score < 0 or v_score > 100 then
    raise exception 'La puntuación no es válida.';
  end if;

  select name into v_display_name
  from public.profiles
  where id = v_user_id;

  if v_display_name is null then
    raise exception 'No se ha encontrado el perfil del usuario.';
  end if;

  v_record := case
    when v_score >= 95 then '18-0'
    when v_score >= 90 then '17-1'
    when v_score >= 84 then '16-2'
    when v_score >= 78 then '15-3'
    when v_score >= 70 then '13-5'
    when v_score >= 60 then '10-8'
    else 'Temporada complicada'
  end;

  insert into public.eighteen_zero_scores (
    user_id, display_name, best_score, last_score, best_record, games_played, updated_at
  ) values (
    v_user_id, v_display_name, v_score, v_score, v_record, 1, now()
  )
  on conflict (user_id) do update set
    display_name = excluded.display_name,
    best_score = greatest(public.eighteen_zero_scores.best_score, excluded.best_score),
    last_score = excluded.last_score,
    best_record = case
      when excluded.best_score > public.eighteen_zero_scores.best_score then excluded.best_record
      else public.eighteen_zero_scores.best_record
    end,
    games_played = public.eighteen_zero_scores.games_played + 1,
    updated_at = now();
end;
$$;

revoke execute on function public.submit_eighteen_zero_score(numeric) from public, anon;
grant execute on function public.submit_eighteen_zero_score(numeric) to authenticated;

drop policy if exists players_public_read on public.players;
create policy players_public_read on public.players for select using (true);

drop policy if exists matches_public_read on public.matches;
create policy matches_public_read on public.matches for select using (true);

drop policy if exists player_stats_public_read on public.player_stats;
create policy player_stats_public_read on public.player_stats for select using (true);

drop policy if exists players_admin_write on public.players;
create policy players_admin_write on public.players for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
)
with check (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists matches_admin_write on public.matches;
create policy matches_admin_write on public.matches for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
)
with check (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists player_stats_admin_write on public.player_stats;
create policy player_stats_admin_write on public.player_stats for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
)
with check (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists contact_messages_insert_public on public.contact_messages;
create policy contact_messages_insert_public on public.contact_messages
for insert to anon, authenticated
with check (
  status = 'new'
  and length(trim(name)) between 2 and 120
  and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  and length(trim(reason)) between 10 and 3000
);

drop policy if exists contact_messages_admin_read on public.contact_messages;
create policy contact_messages_admin_read on public.contact_messages for select using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists contact_messages_admin_update on public.contact_messages;
create policy contact_messages_admin_update on public.contact_messages for update using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
)
with check (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists news_posts_public_read on public.news_posts;
drop policy if exists news_posts_admin_read on public.news_posts;
drop policy if exists news_posts_admin_write on public.news_posts;

create policy news_posts_public_read on public.news_posts
for select
to anon, authenticated
using (published = true);

create policy news_posts_admin_read on public.news_posts
for select
to authenticated
using (public.current_user_role() = 'admin');

create policy news_posts_admin_write on public.news_posts
for all
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'news-images',
  'news-images',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists news_images_public_read on storage.objects;
drop policy if exists news_images_admin_read on storage.objects;
create policy news_images_admin_read on storage.objects
for select
to authenticated
using (
  bucket_id = 'news-images'
  and public.current_user_role() = 'admin'
);

drop policy if exists news_images_admin_insert on storage.objects;
create policy news_images_admin_insert on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'news-images'
  and public.current_user_role() = 'admin'
);

drop policy if exists news_images_admin_update on storage.objects;
create policy news_images_admin_update on storage.objects
for update
to authenticated
using (
  bucket_id = 'news-images'
  and public.current_user_role() = 'admin'
)
with check (
  bucket_id = 'news-images'
  and public.current_user_role() = 'admin'
);

drop policy if exists news_images_admin_delete on storage.objects;
create policy news_images_admin_delete on storage.objects
for delete
to authenticated
using (
  bucket_id = 'news-images'
  and public.current_user_role() = 'admin'
);

drop policy if exists site_content_public_read on public.site_content;
create policy site_content_public_read on public.site_content for select using (true);

drop policy if exists site_content_admin_write on public.site_content;
create policy site_content_admin_write on public.site_content for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
)
with check (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists banquiger_teams_authenticated_read on public.banquiger_teams;
create policy banquiger_teams_authenticated_read on public.banquiger_teams
for select using (auth.role() = 'authenticated');

drop policy if exists banquiger_teams_owner_write on public.banquiger_teams;
create policy banquiger_teams_owner_write on public.banquiger_teams
for all using (
  user_id = auth.uid()
  or exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
)
with check (
  user_id = auth.uid()
  or exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists banquiger_rosters_authenticated_read on public.banquiger_rosters;
create policy banquiger_rosters_authenticated_read on public.banquiger_rosters
for select using (auth.role() = 'authenticated');

drop policy if exists banquiger_rosters_owner_write on public.banquiger_rosters;
create policy banquiger_rosters_owner_write on public.banquiger_rosters
for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  or exists (
    select 1 from public.banquiger_teams
    where banquiger_teams.id = banquiger_rosters.team_id
      and banquiger_teams.user_id = auth.uid()
  )
)
with check (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  or exists (
    select 1 from public.banquiger_teams
    where banquiger_teams.id = banquiger_rosters.team_id
      and banquiger_teams.user_id = auth.uid()
  )
);

revoke execute on function public.current_user_role() from public, anon;
grant execute on function public.current_user_role() to authenticated;

-- App privada de toma de estadísticas.
create table if not exists public.stats_permissions (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  can_capture boolean not null default false,
  notes text,
  updated_at timestamptz not null default now()
);

create table if not exists public.stats_sessions (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references public.profiles(id) on delete cascade,
  mode text not null default 'simple' check (mode in ('simple', 'connected')),
  team text not null check (team in ('masculine', 'feminine')),
  opponent text not null,
  match_id bigint references public.matches(id) on delete set null,
  status text not null default 'draft' check (status in ('draft', 'captured', 'synced', 'reviewed', 'archived')),
  summary jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stats_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.stats_sessions(id) on delete cascade,
  player_id bigint,
  player_name text,
  action text not null,
  value numeric not null default 0,
  period text,
  happened_at timestamptz not null default now(),
  sort_order integer not null default 0,
  x numeric,
  y numeric,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.stats_settings (
  id text primary key check (id = 'global'),
  active_season text not null default '2025-2026'
    check (active_season ~ '^[0-9]{4}-[0-9]{4}$'),
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.stats_settings (id, active_season)
values ('global', '2025-2026')
on conflict (id) do nothing;

alter table public.stats_permissions enable row level security;
alter table public.stats_sessions enable row level security;
alter table public.stats_events enable row level security;
alter table public.stats_settings enable row level security;

drop policy if exists stats_permissions_owner_or_admin_read on public.stats_permissions;
create policy stats_permissions_owner_or_admin_read on public.stats_permissions
for select to authenticated
using (user_id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists stats_permissions_admin_write on public.stats_permissions;
create policy stats_permissions_admin_write on public.stats_permissions
for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists stats_settings_authenticated_read on public.stats_settings;
create policy stats_settings_authenticated_read on public.stats_settings
for select to authenticated using (true);

drop policy if exists stats_settings_admin_write on public.stats_settings;
create policy stats_settings_admin_write on public.stats_settings
for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists stats_sessions_owner_or_admin_read on public.stats_sessions;
create policy stats_sessions_owner_or_admin_read on public.stats_sessions
for select to authenticated
using (created_by = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists stats_sessions_keeper_insert on public.stats_sessions;
create policy stats_sessions_keeper_insert on public.stats_sessions
for insert to authenticated
with check (
  created_by = auth.uid()
  and (
    public.current_user_role() = 'admin'
    or exists (
      select 1
      from public.stats_permissions
      where user_id = auth.uid()
        and can_capture = true
    )
  )
);

drop policy if exists stats_sessions_owner_or_admin_update on public.stats_sessions;
create policy stats_sessions_owner_or_admin_update on public.stats_sessions
for update to authenticated
using (created_by = auth.uid() or public.current_user_role() = 'admin')
with check (created_by = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists stats_events_session_owner_or_admin_read on public.stats_events;
create policy stats_events_session_owner_or_admin_read on public.stats_events
for select to authenticated
using (
  exists (
    select 1
    from public.stats_sessions
    where stats_sessions.id = stats_events.session_id
      and (stats_sessions.created_by = auth.uid() or public.current_user_role() = 'admin')
  )
);

drop policy if exists stats_events_session_owner_insert on public.stats_events;
create policy stats_events_session_owner_insert on public.stats_events
for insert to authenticated
with check (
  exists (
    select 1
    from public.stats_sessions
    where stats_sessions.id = stats_events.session_id
      and stats_sessions.created_by = auth.uid()
  )
);

drop policy if exists stats_events_session_owner_or_admin_delete on public.stats_events;
create policy stats_events_session_owner_or_admin_delete on public.stats_events
for delete to authenticated
using (
  exists (
    select 1
    from public.stats_sessions
    where stats_sessions.id = stats_events.session_id
      and (stats_sessions.created_by = auth.uid() or public.current_user_role() = 'admin')
  )
);
