create table if not exists public.web_analytics_events (
  id bigint generated by default as identity primary key,
  session_id uuid,
  path text not null,
  title text,
  referrer text,
  device text not null default 'unknown' check (device in ('desktop', 'tablet', 'mobile', 'unknown')),
  language text,
  screen_width integer,
  created_at timestamptz not null default now()
);

create index if not exists web_analytics_events_created_at_idx
on public.web_analytics_events (created_at desc);

create index if not exists web_analytics_events_path_idx
on public.web_analytics_events (path);

create index if not exists web_analytics_events_session_id_idx
on public.web_analytics_events (session_id);

alter table public.web_analytics_events enable row level security;

drop policy if exists web_analytics_events_admin_select on public.web_analytics_events;
create policy web_analytics_events_admin_select
on public.web_analytics_events
for select
to authenticated
using (private.current_user_role() = 'admin');

drop policy if exists web_analytics_events_public_insert on public.web_analytics_events;
create policy web_analytics_events_public_insert
on public.web_analytics_events
for insert
to anon, authenticated
with check (
  path is not null
  and length(path) between 1 and 500
  and (title is null or length(title) <= 180)
  and (referrer is null or length(referrer) <= 500)
  and (language is null or length(language) <= 32)
  and (screen_width is null or screen_width between 0 and 10000)
  and device in ('desktop', 'tablet', 'mobile', 'unknown')
);

revoke all on table public.web_analytics_events from anon, authenticated;
grant insert on table public.web_analytics_events to anon, authenticated;
grant select on table public.web_analytics_events to authenticated;

create or replace function public.track_web_visit(
  p_session_id uuid,
  p_path text,
  p_title text default null,
  p_referrer text default null,
  p_language text default null,
  p_screen_width integer default null,
  p_device text default 'unknown'
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_path text := left(coalesce(nullif(trim(p_path), ''), '/'), 500);
  v_device text := lower(coalesce(nullif(trim(p_device), ''), 'unknown'));
begin
  if v_device not in ('desktop', 'tablet', 'mobile', 'unknown') then
    v_device := 'unknown';
  end if;

  insert into public.web_analytics_events (
    session_id,
    path,
    title,
    referrer,
    language,
    screen_width,
    device
  )
  values (
    p_session_id,
    v_path,
    left(nullif(trim(coalesce(p_title, '')), ''), 180),
    left(nullif(trim(coalesce(p_referrer, '')), ''), 500),
    left(nullif(trim(coalesce(p_language, '')), ''), 32),
    case
      when p_screen_width is null then null
      when p_screen_width between 0 and 10000 then p_screen_width
      else null
    end,
    v_device
  );
end;
$$;

revoke execute on function public.track_web_visit(uuid, text, text, text, text, integer, text) from public;
grant execute on function public.track_web_visit(uuid, text, text, text, text, integer, text) to anon, authenticated;
